name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iMusic.Client/
    
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
      
    - name:  Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: './iMusic.Client/package-lock.json'
      
    - name: CI
      run: npm ci
      
    - name: Run tests
      run: npm test
