name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Navigate to Angular project folder
      run: cd iMusic.Client
      
    - name:  Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
      
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build:prod
      
    - name: Run tests
      run: npm test
