name: FrontEnd CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './iMusic.Client/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./iMusic.Client/

      - name: Check for Angular CLI
        run: npm install -g @angular/cli
        working-directory: ./iMusic.Client/

      - name: Build Angular application
        run: ng build --configuration production # Use --configuration production for optimized build
        working-directory: ./iMusic.Client/

      - name: List dist contents
        run: ls -lR dist
        working-directory: ./iMusic.Client/ # VERY IMPORTANT

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'imusic-frontend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: './iMusic.Client/dist' # Adjusted package path
